// Code generated by http-gen compiler. DO NOT EDIT.
// source: aihot-server.idl
// argument: --client_style=protoc

package error

import (
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

const (
	// ErrOk 成功
	ErrOk codes.Code = 0
	// PARAM_ERROR 参数错误
	PARAM_ERROR codes.Code = 8304001
)

// Msg 异常消息映射表
var Msg = map[codes.Code]string{
	ErrOk:       "成功",
	PARAM_ERROR: "参数错误",
}

var (
	// GrpcErrOk 成功
	GrpcErrOk = status.Errorf(ErrOk, "成功")
	// GrpcPARAM_ERROR 参数错误
	GrpcPARAM_ERROR = status.Errorf(PARAM_ERROR, "参数错误")
)
