// Code generated by http-gen compiler. DO NOT EDIT.
// source: aihot-server.idl
// argument: --client_style=protoc

package proto

import (
	"fmt"
	"git.xiaojukeji.com/nuwa/golibs/json"
	"reflect"
)

var _ = fmt.Printf

func init() {
	json.Pretouch(reflect.TypeOf((*PingReq)(nil)))
	json.Pretouch(reflect.TypeOf((*PingRsp)(nil)))
}

func StrPtr(s string) *string       { return &s }
func Int8Ptr(s int8) *int8          { return &s }
func Int32Ptr(s int32) *int32       { return &s }
func Int64Ptr(s int64) *int64       { return &s }
func Int16Ptr(s int16) *int16       { return &s }
func IntPtr(s int) *int             { return &s }
func BoolPtr(s bool) *bool          { return &s }
func Float64Ptr(s float64) *float64 { return &s }
func Float32Ptr(s float32) *float32 { return &s }

type ErrCode int32

const (
	ErrCode_ErrOk       ErrCode = 0       // 成功
	ErrCode_PARAM_ERROR ErrCode = 8304001 // 参数错误
)

var (
	ErrCode_name = map[int32]string{
		0:       "ErrOk",
		8304001: "PARAM_ERROR",
	}
	ErrCode_value = map[string]int32{
		"ErrOk":       0,
		"PARAM_ERROR": 8304001,
	}
)

func OneOfErrCode(i int32) bool {
	_, ok := ErrCode_name[i]
	return ok
}

/** IDL编写规范：http://wiki.intra.xiaojukeji.com/pages/viewpage.action?pageId=120245837 */
/** Ping请求 */
type PingReq struct {
	Name string `json:"name" form:"name"` //姓名
}

func (x *PingReq) GetName() (r string) {
	if x != nil {
		return x.Name
	}
	return r
}

func (x *PingReq) SetName(v string) {
	if x != nil {
		x.Name = v
	}
}

func (p *PingReq) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PingReq(%+v)", *p)
}

/** Ping返回 */
type PingRsp struct {
	Errno  int32  `json:"errno" form:"errno"`   //错误码
	Errmsg string `json:"errmsg" form:"errmsg"` //错误信息
	Data   string `json:"data" form:"data"`     //返回值
}

func (x *PingRsp) GetErrno() (r int32) {
	if x != nil {
		return x.Errno
	}
	return r
}

func (x *PingRsp) GetErrmsg() (r string) {
	if x != nil {
		return x.Errmsg
	}
	return r
}

func (x *PingRsp) GetData() (r string) {
	if x != nil {
		return x.Data
	}
	return r
}

func (x *PingRsp) SetErrno(v int32) {
	if x != nil {
		x.Errno = v
	}
}

func (x *PingRsp) SetErrmsg(v string) {
	if x != nil {
		x.Errmsg = v
	}
}

func (x *PingRsp) SetData(v string) {
	if x != nil {
		x.Data = v
	}
}

func (p *PingRsp) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("PingRsp(%+v)", *p)
}
