// Code generated by http-gen compiler. DO NOT EDIT.
// source: aihot-server.idl
// argument: --client_style=protoc

// Package proto is the logic of http server.
package proto

import (
	"context"
	"fmt"
	"io"
	"net/http"
	"strconv"

	legoTrace "git.xiaojukeji.com/lego/context-go"
	"git.xiaojukeji.com/nuwa/binding"
	"git.xiaojukeji.com/nuwa/golibs/rpcserver/v2/rpcserver"
	"github.com/grpc-ecosystem/grpc-gateway/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/utilities"
)

var _ io.Reader
var _ fmt.State
var _ legoTrace.Trace
var _ strconv.NumError

const ErrNo = "errno"
const Errmsg = "errmsg"

type reqKeyStruct struct{}
type respHeaderKeyStruct struct{}
type respHttpCodeKeyStruct struct{}

func init() {
	rpcserver.EnableNuwaJson()
}

var (
	reqKey          reqKeyStruct
	respHeaderKey   respHeaderKeyStruct
	respHttpCodeKey respHttpCodeKeyStruct
)

func toString(i interface{}) string {
	switch v := i.(type) {
	case nil:
		return ""
	case *int:
		return strconv.FormatInt(int64(*v), 10)
	case *int32:
		return strconv.FormatInt(int64(*v), 10)
	case *int64:
		return strconv.FormatInt(int64(*v), 10)
	case int:
		return strconv.FormatInt(int64(v), 10)
	case int32:
		return strconv.FormatInt(int64(v), 10)
	case int64:
		return strconv.FormatInt(int64(v), 10)
	case *string:
		return *v
	case string:
		return v
	default:
		return fmt.Sprint(i)
	}
}

func setTraceCustomKV(ctx context.Context, key, val string) {
	r, _ := legoTrace.GetCtxTrace(ctx)
	if r != nil {
		r.SetCustomKV(key, val)
	}
}

// GetHeader used for get requestHeader
func GetHeader(ctx context.Context, key string) string {
	req := GetReq(ctx)
	if req != nil {
		return req.Header.Get(key)
	}
	return ""
}

// GetReq used for get request from ctx
func GetReq(ctx context.Context) *http.Request {
	req, ok := ctx.Value(reqKey).(*http.Request)
	if !ok {
		return nil
	}
	return req
}

// SetHeader used for set respHeader
func SetHeader(ctx context.Context, key, value string) {
	headers, ok := ctx.Value(respHeaderKey).(http.Header)
	if ok {
		headers.Add(key, value)
	}
}

// SetCookie used for set cookie in respHeader
func SetCookie(ctx context.Context, cookie *http.Cookie) {
	if v := cookie.String(); v != "" {
		headers, ok := ctx.Value(respHeaderKey).(http.Header)
		if ok {
			headers.Add("Set-Cookie", v)
		}
	}
}

// SetHttpCode used for set httpCode
func SetHttpCode(ctx context.Context, httpCode int) {
	if code, ok := ctx.Value(respHttpCodeKey).(*int); ok {
		*code = httpCode
		_ = code
	}
	return
}

func handleForwardHeader(ctx context.Context, w http.ResponseWriter) {
	headers, ok := ctx.Value(respHeaderKey).(http.Header)
	if ok {
		for k, vs := range headers {
			for _, v := range vs {
				w.Header().Add(k, v)
			}
		}
	}
}

// NuwaSSEResp 占位用结构体
type NuwaSSEResp struct{}

// ResponseFlusher 为 sse 类型接口准备的 writer 和 flusher 复合接口
type ResponseFlusher interface {
	http.ResponseWriter
	http.Flusher
}

var respFlusherKey int

// getResponseFlusher 获取 ctx 上的 ResponseFlusher 对象
func getResponseFlusher(ctx context.Context) ResponseFlusher {
	w, _ := ctx.Value(&respFlusherKey).(ResponseFlusher)
	return w
}

// setResponseFlusher 为 ctx 绑定 setResponseFlusher 对象
func setResponseFlusher(ctx context.Context, w ResponseFlusher) context.Context {
	return context.WithValue(ctx, &respFlusherKey, w)
}

type AihotServerServer interface {
	ChatAI(context.Context, *PingReq, ResponseFlusher)
	Ping(context.Context, *PingReq) (*PingRsp, error)
}

type AihotServerServerNoError interface {
	ChatAI(context.Context, *PingReq, ResponseFlusher)
	Ping(context.Context, *PingReq) *PingRsp
}

type AihotServerServerWrapper struct {
	Server AihotServerServerNoError
}

func (s *AihotServerServerWrapper) ChatAI(ctx context.Context, req *PingReq, w ResponseFlusher) {
	s.Server.ChatAI(ctx, req, w)
}

func (s *AihotServerServerWrapper) Ping(ctx context.Context, req *PingReq) (*PingRsp, error) {
	return s.Server.Ping(ctx, req), nil
}

var methodOptions struct {
	requestParserForChatAI func(req *http.Request, pathParams map[string]string) (PingReq, error)
	requestParserForPing   func(req *http.Request, pathParams map[string]string) (PingReq, error)

	parseBodyAndQueryStrForChatAI bool
	parseBodyAndQueryStrForPing   bool
}

func SetRequestParserForChatAI(p func(req *http.Request, pathParams map[string]string) (PingReq, error)) {
	methodOptions.requestParserForChatAI = p
}

func EnableBothParseBodyAndQueryStrForChatAI(enable bool) {
	methodOptions.parseBodyAndQueryStrForChatAI = enable
}

func SetRequestParserForPing(p func(req *http.Request, pathParams map[string]string) (PingReq, error)) {
	methodOptions.requestParserForPing = p
}

func EnableBothParseBodyAndQueryStrForPing(enable bool) {
	methodOptions.parseBodyAndQueryStrForPing = enable
}

var marshalOptions struct {
	responseMarshalerForPing func(ctx context.Context, resp *PingRsp) (ret interface{})
}

func SetResponseMarshalerForPing(p func(ctx context.Context, resp *PingRsp) (ret interface{})) {
	marshalOptions.responseMarshalerForPing = p
}

var (
	filter_AihotServer_ChatAI_0 = &utilities.DoubleArray{Encoding: map[string]int{"": 0}, Base: []int{1, 1, 0}, Check: []int{0, 1, 2}}
)

func local_request_AihotServer_ChatAI_0(ctx context.Context, marshaler runtime.Marshaler, server AihotServerServer, req *http.Request, pathParams map[string]string) (*NuwaSSEResp, error) {
	var protoReq PingReq

	if methodOptions.requestParserForChatAI != nil {
		var err error
		if protoReq, err = methodOptions.requestParserForChatAI(req, pathParams); err != nil {
			return nil, fmt.Errorf("requestParserForChatAI err, %v", err)
		}
	} else {
		if methodOptions.parseBodyAndQueryStrForChatAI {
			if err := req.ParseForm(); err != nil {
				return nil, fmt.Errorf("ParseForm err, err %v", err)
			}

			if err := binding.ShouldBindQuery(req, &protoReq); err != nil {
				return nil, fmt.Errorf("PopulateQueryParameters err, err %v", err)
			}
		}

		newReader, berr := utilities.IOReaderFactory(req.Body)
		if berr != nil {
			return nil, berr
		}
		if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
			return nil, err
		}
	}

	w := getResponseFlusher(ctx)
	server.ChatAI(ctx, &protoReq, w)
	return nil, nil
}

var (
	filter_AihotServer_Ping_0 = &utilities.DoubleArray{Encoding: map[string]int{}, Base: []int(nil), Check: []int(nil)}
)

func local_request_AihotServer_Ping_0(ctx context.Context, marshaler runtime.Marshaler, server AihotServerServer, req *http.Request, pathParams map[string]string) (*PingRsp, error) {
	var protoReq PingReq

	if methodOptions.requestParserForPing != nil {
		var err error
		if protoReq, err = methodOptions.requestParserForPing(req, pathParams); err != nil {
			return nil, fmt.Errorf("requestParserForPing err, %v", err)
		}
	} else {
		if err := req.ParseForm(); err != nil {
			return nil, fmt.Errorf("ParseForm err, err %v", err)
		}

		if err := binding.ShouldBindQuery(req, &protoReq); err != nil {
			return nil, fmt.Errorf("PopulateQueryParameters err, err %v", err)
		}

		newReader, berr := utilities.IOReaderFactory(req.Body)
		if berr != nil {
			return nil, berr
		}
		if err := marshaler.NewDecoder(newReader()).Decode(&protoReq); err != nil && err != io.EOF {
			return nil, err
		}
	}

	msg, err := server.Ping(ctx, &protoReq)
	if msg != nil {
		setTraceCustomKV(req.Context(), ErrNo, toString(msg.Errno))
		setTraceCustomKV(req.Context(), Errmsg, toString(msg.Errmsg))
	}

	return msg, err
}

// RegisterAihotServerServer registers the http handlers for service AihotServer to "mux".
func RegisterAihotServerHandlerServer(ctx context.Context, mux *runtime.ServeMux, server AihotServerServer) error {

	mux.Handle("POST", pattern_AihotServer_ChatAI_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()

		if calleeFunc := req.Header.Get(legoTrace.DiRPC_HEADER_CALLEE_FUNC); calleeFunc == "" {
			req.Header.Set(legoTrace.DiRPC_HEADER_CALLEE_FUNC, pattern_AihotServer_ChatAI_0.String())
		}

		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)

		if _, ok := w.(http.Flusher); !ok {
			err := fmt.Errorf("streaming unsupported!")
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		ctx = setResponseFlusher(ctx, w.(ResponseFlusher))

		var defaultHttpCode = 200
		ctx = context.WithValue(ctx, reqKey, req)
		ctx = context.WithValue(ctx, respHeaderKey, http.Header{})
		ctx = context.WithValue(ctx, respHttpCodeKey, &defaultHttpCode)
		resp, err := local_request_AihotServer_ChatAI_0(ctx, inboundMarshaler, server, req, pathParams)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		_ = resp
	})

	mux.Handle("GET", pattern_AihotServer_Ping_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()

		if calleeFunc := req.Header.Get(legoTrace.DiRPC_HEADER_CALLEE_FUNC); calleeFunc == "" {
			req.Header.Set(legoTrace.DiRPC_HEADER_CALLEE_FUNC, pattern_AihotServer_Ping_0.String())
		}

		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)

		var defaultHttpCode = 200
		ctx = context.WithValue(ctx, reqKey, req)
		ctx = context.WithValue(ctx, respHeaderKey, http.Header{})
		ctx = context.WithValue(ctx, respHttpCodeKey, &defaultHttpCode)
		resp, err := local_request_AihotServer_Ping_0(ctx, inboundMarshaler, server, req, pathParams)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		contentType := outboundMarshaler.ContentType()
		w.Header().Set("Content-Type", contentType)
		handleForwardHeader(ctx, w)

		var ri interface{} = resp
		if marshalOptions.responseMarshalerForPing != nil {
			ri = marshalOptions.responseMarshalerForPing(ctx, resp)
		}

		buf, err := outboundMarshaler.Marshal(ri)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		code := ctx.Value(respHttpCodeKey)
		if httpCode, ok := code.(*int); ok {
			w.WriteHeader(*httpCode)
		}

		if _, err = w.Write(buf); err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
		}
	})

	return nil
}

var (
	pattern_AihotServer_ChatAI_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0}, []string{"chatAI"}, ""))

	pattern_AihotServer_Ping_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0}, []string{"ping"}, ""))
)
